### ISSUE TITLE
Patched?

### ISSUE THREAD

**Issue by DragonFlames638** [ThatFruedDued/blooket-hack#3]
All game codes not reconized. regardless of when game was created. Script was tested on icognito mode on a personal laptop, so no blockers should be interfering

**Comment by TheFinality** [comment]
He hasnt updated yet

**Comment by ThatFruedDued** [comment]
I am aware of this issue. The hack was not patched, the Blooket version it uses just needs to be updated to support new server-side functionality. However, updating is a long and tedious process, so I will be waiting until the next major release of Blooket (season 3) to release before updating. Sorry for the wait!

**Comment by projohnits** [comment]
hello

**Comment by TheFinality** [comment]
Are you going to be annoying here as well? *if u dont know what I'm talking about, he legit made an issue asking who hates someone*

**Comment by ThatFruedDued** [comment]
The update should be done by the end of today

**Comment by ThatFruedDued** [comment]
Fixed
