### ISSUE TITLE
Not an issue just a suggestion

### ISSUE THREAD

**Issue by spencerhonsspam123** [ThatFruedDued/blooket-hack#5]
Here’s a good suggestion that may or may not be too hard
In gold rush, make it so that no one can steal or swap from you. Like your name just doesn’t show up on the screen when you go to steal/swap the coins.
Idk if this is possible but it’s so annoying when you have zillions of coins and somebody just swaps with you. But yeah.

**Comment by Aethese** [comment]
not possible, that's handled server side

**Comment by spencerhonsspam123** [comment]
Or maybe try lowering everybody else’s chances of getting the swap power up?

**Comment by Aethese** [comment]
also not possible. their chances are calculated locally (i presume)

**Comment by spencerhonsspam123** [comment]
Make it look like you have no coins, but you really have a lot more?
Sorry, I’m not very good at coding

**Comment by DragonFlames638** [comment]
> Make it look like you have no coins, but you really have a lot more?
> 
> Sorry, I’m not very good at coding

Changing the coins directly would be a server side change

**Comment by DragonFlames638** [comment]
> change

(Which is very hard or not possible)

**Comment by spencerhonsspam123** [comment]
Oh. Ok. Maybe increase chances of quadrupling coins?

**Comment by Aethese** [comment]
i'm pretty sure their already is a built in feature that makes you more "lucky". if not it at least removes option to get a negative effect

**Comment by spencerhonsspam123** [comment]
There is an effect to remove all negative outcomes but it would be awesome to always get triple, double, quadrupole coins from chests.

**Comment by Aethese** [comment]
the options currently are: remove negatives and double prizes. i think these additions are fine and will give you a good advantage against your peers :)

**Comment by spencerhonsspam123** [comment]
True and ya they are a good advantage but then people just swap coins and I’m right back where I started, and also getting 20-100 coins

**Comment by Aethese** [comment]
it wouldn't be fun if you weren't getting fucked over too ;)

**Comment by spencerhonsspam123** [comment]
Very true lol

**Comment by ThatFruedDued** [comment]
Sorry, the original suggestion is not possible because that is handled server-side. I may look into increasing odds of better prizes next time Blooket updates.
