### ISSUE TITLE
Suggestion: support for Crypto hack?

### ISSUE THREAD

**Issue by spencerhonsspam123** [ThatFruedDued/blooket-hack#6]
Maybe some mods for crypto hack, if possible, like make it show the correct password all the time.

**Comment by ThatFruedDued** [comment]
Yes, I may do this.
Expect more active updates in this repository after Season 3 releases (scheduled for tomorrow).

**Comment by spencerhonsspam123** [comment]
Thank you for responding. Also maybe not just the passwords, maybe the answers for the questions In almost all gamemodes if you can. This would be funny as everybody is struggling but I’m cruising ;)
Or not show the answers but make every answer always correct?

**Comment by ThatFruedDued** [comment]
Support has been added.
