### ISSUE TITLE
Just another suggestion

### ISSUE THREAD

**Issue by spencerhonsspam123** [ThatFruedDued/blooket-hack#7]
(This is just going off of the crypto hack suggestion) maybe not just the passwords, maybe the answers for the questions In almost all gamemodes if you can. This would be funny as everybody is struggling but I’m cruising ;)
Or not show the answers but make every answer always correct?

**Comment by glixzzy** [comment]
I think you are missing out... I have a cheat that gives you other users correct password: https://github.com/glixzzy/blooket-hack/tree/main/crypto and a cheat that makes your answer correct even if you pick the wrong one: https://github.com/glixzzy/blooket-hack/tree/main/global

**Comment by spencerhonsspam123** [comment]
I’m not denying that, but I use an iPad and I can’t use developer console, but bookmarklets work in Google Chrome, or else I would use ur cheats. So if we could convert your code into a bookmarklet, that would be AWESOME.

**Comment by spencerhonsspam123** [comment]
I saw ur bookmarklet tutorial but the give crypto bookmark doesn’t work?

**Comment by glixzzy** [comment]
yeah i made some mistakes please make issues about my stuff in my repo, i dont want my stuff to be affiliated with this repo

**Comment by ThatFruedDued** [comment]
The 'All Answers Correct' feature has been added.
